[2024-06-07T10:53:56.767+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T10:53:56.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_data_daily.scrape_and_upload_to_s3_task scheduled__2024-01-23T00:00:00+00:00 [queued]>
[2024-06-07T10:53:56.844+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_data_daily.scrape_and_upload_to_s3_task scheduled__2024-01-23T00:00:00+00:00 [queued]>
[2024-06-07T10:53:56.847+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-07T10:53:56.900+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scrape_and_upload_to_s3_task> on 2024-01-23 00:00:00+00:00
[2024-06-07T10:53:56.910+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3040) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T10:53:56.913+0000] {standard_task_runner.py:63} INFO - Started process 3048 to run task
[2024-06-07T10:53:56.913+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'scrape_data_daily', 'scrape_and_upload_to_s3_task', 'scheduled__2024-01-23T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/Exchange_rate_dag.py', '--cfg-path', '/tmp/tmp45on82tv']
[2024-06-07T10:53:56.916+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask scrape_and_upload_to_s3_task
[2024-06-07T10:53:57.026+0000] {task_command.py:426} INFO - Running <TaskInstance: scrape_data_daily.scrape_and_upload_to_s3_task scheduled__2024-01-23T00:00:00+00:00 [running]> on host 50a1f90d0296
[2024-06-07T10:53:57.581+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_data_daily' AIRFLOW_CTX_TASK_ID='scrape_and_upload_to_s3_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-23T00:00:00+00:00'
[2024-06-07T10:53:57.595+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T10:54:01.956+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T10:54:01.977+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Exchange_rate_dag.py", line 36, in scrape_and_upload_to_s3
    new_data = scrape_data(url)
               ^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/scrape_data.py", line 29, in scrape_data
    df.columns = ['Date', 'Currency', 'Buying_Rate', 'Selling_Rate']
    ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 6 elements, new values have 4 elements
[2024-06-07T10:54:02.316+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_data_daily, task_id=scrape_and_upload_to_s3_task, run_id=scheduled__2024-01-23T00:00:00+00:00, execution_date=20240123T000000, start_date=20240607T105356, end_date=20240607T105402
[2024-06-07T10:54:02.776+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 65 for task scrape_and_upload_to_s3_task (Length mismatch: Expected axis has 6 elements, new values have 4 elements; 3048)
[2024-06-07T10:54:02.879+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-07T10:54:02.919+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
