[2024-06-07T10:53:48.545+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T10:53:48.593+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_data_daily.scrape_and_upload_to_s3_task scheduled__2024-01-08T00:00:00+00:00 [queued]>
[2024-06-07T10:53:48.619+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_data_daily.scrape_and_upload_to_s3_task scheduled__2024-01-08T00:00:00+00:00 [queued]>
[2024-06-07T10:53:48.631+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-07T10:53:48.670+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scrape_and_upload_to_s3_task> on 2024-01-08 00:00:00+00:00
[2024-06-07T10:53:48.681+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3000) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T10:53:48.684+0000] {standard_task_runner.py:63} INFO - Started process 3039 to run task
[2024-06-07T10:53:48.691+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'scrape_data_daily', 'scrape_and_upload_to_s3_task', 'scheduled__2024-01-08T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/Exchange_rate_dag.py', '--cfg-path', '/tmp/tmpt_i44zw_']
[2024-06-07T10:53:48.693+0000] {standard_task_runner.py:91} INFO - Job 63: Subtask scrape_and_upload_to_s3_task
[2024-06-07T10:53:48.801+0000] {task_command.py:426} INFO - Running <TaskInstance: scrape_data_daily.scrape_and_upload_to_s3_task scheduled__2024-01-08T00:00:00+00:00 [running]> on host 50a1f90d0296
[2024-06-07T10:53:49.120+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_data_daily' AIRFLOW_CTX_TASK_ID='scrape_and_upload_to_s3_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-08T00:00:00+00:00'
[2024-06-07T10:53:49.148+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T10:53:52.569+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T10:53:52.586+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Exchange_rate_dag.py", line 36, in scrape_and_upload_to_s3
    new_data = scrape_data(url)
               ^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/scrape_data.py", line 29, in scrape_data
    df.columns = ['Date', 'Currency', 'Buying_Rate', 'Selling_Rate']
    ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 6 elements, new values have 4 elements
[2024-06-07T10:53:52.651+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=scrape_data_daily, task_id=scrape_and_upload_to_s3_task, run_id=scheduled__2024-01-08T00:00:00+00:00, execution_date=20240108T000000, start_date=20240607T105348, end_date=20240607T105352
[2024-06-07T10:53:53.101+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 63 for task scrape_and_upload_to_s3_task (Length mismatch: Expected axis has 6 elements, new values have 4 elements; 3039)
[2024-06-07T10:53:53.129+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-07T10:53:53.165+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-07T10:53:53.181+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
