[2024-06-07T10:52:45.781+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T10:52:45.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_data_daily.scrape_and_upload_to_s3_task manual__2024-06-07T10:51:13.390400+00:00 [queued]>
[2024-06-07T10:52:45.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_data_daily.scrape_and_upload_to_s3_task manual__2024-06-07T10:51:13.390400+00:00 [queued]>
[2024-06-07T10:52:45.909+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-07T10:52:45.940+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scrape_and_upload_to_s3_task> on 2024-06-07 10:51:13.390400+00:00
[2024-06-07T10:52:45.952+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2978) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T10:52:45.957+0000] {standard_task_runner.py:63} INFO - Started process 2984 to run task
[2024-06-07T10:52:45.959+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'scrape_data_daily', 'scrape_and_upload_to_s3_task', 'manual__2024-06-07T10:51:13.390400+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/Exchange_rate_dag.py', '--cfg-path', '/tmp/tmp6ex6dce0']
[2024-06-07T10:52:45.965+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask scrape_and_upload_to_s3_task
[2024-06-07T10:52:46.056+0000] {task_command.py:426} INFO - Running <TaskInstance: scrape_data_daily.scrape_and_upload_to_s3_task manual__2024-06-07T10:51:13.390400+00:00 [running]> on host 50a1f90d0296
[2024-06-07T10:52:46.225+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_data_daily' AIRFLOW_CTX_TASK_ID='scrape_and_upload_to_s3_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T10:51:13.390400+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-07T10:51:13.390400+00:00'
[2024-06-07T10:52:46.252+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T10:52:49.705+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T10:52:49.707+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Exchange_rate_dag.py", line 36, in scrape_and_upload_to_s3
    new_data = scrape_data(url)
               ^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/scrape_data.py", line 29, in scrape_data
    df.columns = ['Date', 'Currency', 'Buying_Rate', 'Selling_Rate']
    ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 6 elements, new values have 4 elements
[2024-06-07T10:52:49.805+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_data_daily, task_id=scrape_and_upload_to_s3_task, run_id=manual__2024-06-07T10:51:13.390400+00:00, execution_date=20240607T105113, start_date=20240607T105245, end_date=20240607T105249
[2024-06-07T10:52:49.860+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task scrape_and_upload_to_s3_task (Length mismatch: Expected axis has 6 elements, new values have 4 elements; 2984)
[2024-06-07T10:52:49.894+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-07T10:52:49.936+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-07T10:52:49.945+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
